export enum Utils {
    TITLE_SUCCESS = 'UTILS.TITLE_SUCCESS',
    TITLE_ERROR = 'UTILS.TITLE_ERROR',
    TITLE_CONFIRM = 'UTILS.TITLE_CONFIRM',
    OK = 'UTILS.OK',
    CLOSE = 'UTILS.CLOSE',
    SAVE = 'UTILS.SAVE'
}